################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
CMSIS/DSP/Source/BasicMathFunctions \
CMSIS/DSP/Source/BayesFunctions \
CMSIS/DSP/Source/CommonTables \
CMSIS/DSP/Source/ComplexMathFunctions \
CMSIS/DSP/Source/ControllerFunctions \
CMSIS/DSP/Source/DistanceFunctions \
CMSIS/DSP/Source/FastMathFunctions \
CMSIS/DSP/Source/FilteringFunctions \
CMSIS/DSP/Source/InterpolationFunctions \
CMSIS/DSP/Source/MatrixFunctions \
CMSIS/DSP/Source/QuaternionMathFunctions \
CMSIS/DSP/Source/SVMFunctions \
CMSIS/DSP/Source/StatisticsFunctions \
CMSIS/DSP/Source/SupportFunctions \
CMSIS/DSP/Source/TransformFunctions \
CMSIS/DSP/Source/WindowFunctions \
CMSIS/NN/Source/ActivationFunctions \
CMSIS/NN/Source/BasicMathFunctions \
CMSIS/NN/Source/ConcatenationFunctions \
CMSIS/NN/Source/ConvolutionFunctions \
CMSIS/NN/Source/FullyConnectedFunctions \
CMSIS/NN/Source/LSTMFunctions \
CMSIS/NN/Source/NNSupportFunctions \
CMSIS/NN/Source/PoolingFunctions \
CMSIS/NN/Source/ReshapeFunctions \
CMSIS/NN/Source/SVDFunctions \
CMSIS/NN/Source/SoftmaxFunctions \
accel \
azure-rtos/levelx/common/src \
azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src/azure/core \
azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src/azure/iot \
azure-rtos/netxduo/addons/azure_iot/azure-sdk-for-c/sdk/src/azure/platform \
azure-rtos/netxduo/addons/azure_iot \
board \
codec \
codec/port/cs42888 \
codec/port/da7212 \
codec/port \
codec/port/sgtl5000 \
codec/port/wm8904 \
codec/port/wm8960 \
component/audio \
component/crc \
component/gpio \
component/i2c \
component/lists \
component/pwm \
component/reset \
component/rng \
component/rtc \
component/serial_manager \
component/spi \
component/timer \
component/uart \
device \
drivers \
fatfs/source \
fatfs/source/fsl_mmc_disk \
fatfs/source/fsl_ram_disk \
fatfs/source/fsl_sd_disk \
fatfs/source/fsl_usb_disk \
freemaster/drivers \
freemaster \
freertos/backoffalgorithm/source \
freertos/corejson/source \
freertos/coremqtt/source \
freertos/coremqtt-agent/source \
freertos/corepkcs11/source \
freertos/corepkcs11/source/dependency/3rdparty/mbedtls_utils \
freertos/corepkcs11/source/portable/mbedtls \
freertos/freertos-kernel/portable/GCC/ARM_CM33/non_secure \
freertos/freertos-kernel/portable/GCC/ARM_CM33/secure \
freertos/freertos-kernel/portable/GCC/ARM_CM33_NTZ/non_secure \
lcdc \
lvgl/lvgl/src/core \
lvgl/lvgl/src/draw \
lvgl/lvgl/src/draw/nxp/pxp \
lvgl/lvgl/src/draw/nxp/vglite \
lvgl/lvgl/src/draw/renesas \
lvgl/lvgl/src/draw/sdl \
lvgl/lvgl/src/draw/stm32_dma2d \
lvgl/lvgl/src/draw/sw \
lvgl/lvgl/src/extra/layouts/flex \
lvgl/lvgl/src/extra/layouts/grid \
lvgl/lvgl/src/extra/libs/bmp \
lvgl/lvgl/src/extra/libs/ffmpeg \
lvgl/lvgl/src/extra/libs/freetype \
lvgl/lvgl/src/extra/libs/fsdrv \
lvgl/lvgl/src/extra/libs/gif \
lvgl/lvgl/src/extra/libs/png \
lvgl/lvgl/src/extra/libs/qrcode \
lvgl/lvgl/src/extra/libs/rlottie \
lvgl/lvgl/src/extra/libs/sjpg \
lvgl/lvgl/src/extra \
lvgl/lvgl/src/extra/others/fragment \
lvgl/lvgl/src/extra/others/gridnav \
lvgl/lvgl/src/extra/others/ime \
lvgl/lvgl/src/extra/others/imgfont \
lvgl/lvgl/src/extra/others/monkey \
lvgl/lvgl/src/extra/others/msg \
lvgl/lvgl/src/extra/others/snapshot \
lvgl/lvgl/src/extra/themes/basic \
lvgl/lvgl/src/extra/themes/default \
lvgl/lvgl/src/extra/themes/mono \
lvgl/lvgl/src/extra/widgets/animimg \
lvgl/lvgl/src/extra/widgets/calendar \
lvgl/lvgl/src/extra/widgets/chart \
lvgl/lvgl/src/extra/widgets/colorwheel \
lvgl/lvgl/src/extra/widgets/imgbtn \
lvgl/lvgl/src/extra/widgets/keyboard \
lvgl/lvgl/src/extra/widgets/led \
lvgl/lvgl/src/extra/widgets/list \
lvgl/lvgl/src/extra/widgets/menu \
lvgl/lvgl/src/extra/widgets/meter \
lvgl/lvgl/src/extra/widgets/msgbox \
lvgl/lvgl/src/extra/widgets/span \
lvgl/lvgl/src/extra/widgets/spinbox \
lvgl/lvgl/src/extra/widgets/spinner \
lvgl/lvgl/src/extra/widgets/tabview \
lvgl/lvgl/src/extra/widgets/tileview \
lvgl/lvgl/src/extra/widgets/win \
lvgl/lvgl/src/font \
lvgl/lvgl/src/hal \
lvgl/lvgl/src/misc \
lvgl/lvgl/src/widgets \
maestro/ogg/src \
maestro/opus/celt \
maestro/opus/silk \
maestro/opus/silk/fixed \
maestro/opus/src \
maestro/opusfile/src \
maestro/streamer/cci/metadata/src/aac \
maestro/streamer/cci/metadata/src/adpcm \
maestro/streamer/cci/metadata/src/flac \
maestro/streamer/cci/metadata/src/mp3 \
maestro/streamer/cci/metadata/src/opus \
maestro/streamer/core \
maestro/streamer/decoders/cci_dec \
maestro/streamer/devices \
maestro/streamer/elements \
maestro/streamer/encoders/opus \
maestro/streamer/parsers/cci \
maestro/streamer/utils \
mbedtls/library \
mbedtls/port/ksdk \
mcmgr \
pmic_driver \
sdmmc/host \
sdmmc/osa \
sdmmc/src \
source \
startup \
tinycbor/src \
usb/device/class/audio \
usb/device/class/ccid \
usb/device/class/cdc \
usb/device/class/cdc_rndis \
usb/device/class/dfu \
usb/device/class/hid \
usb/device/class/msc \
usb/device/class/phdc \
usb/device/class/printer \
usb/device/class \
usb/device/class/video \
usb/device/source/lpcip3511 \
usb/device/source \
usb/host/class \
usb/host \
usb/pd/altmode \
usb/pd \
usb/phy \
usb/phy_interface \
usb/ptn5110 \
utilities \

